import { Hono } from 'hono'
import { existsSync, readFileSync } from 'fs'
import { resolve } from 'path'

export const agentCardRoute = new Hono()

// Serve ERC-8004 metadata (generated by setup TUI → data/agent-metadata.json)
agentCardRoute.get('/agent.json', (c) => {
  // data/ is at project root; when run via `bun run --cwd apps/server`, cwd = apps/server
  const dataPath = resolve(process.cwd(), '../../data/agent-metadata.json')
  if (existsSync(dataPath)) {
    const raw = readFileSync(dataPath, 'utf-8')
    return c.json(JSON.parse(raw))
  }
  // Fallback minimal jika file belum ada
  return c.json({
    type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1',
    name: 'Kinko',
    description: 'AI agent funded by Solana staking yield.',
    services: [],
    active: true,
    registrations: [],
    supportedTrust: ['crypto-economic'],
  })
})

agentCardRoute.get('/agent-card.json', (c) => {
  return c.json({
    protocolVersion: '0.3.0',
    name: 'Kinko',
    description: 'AI agent funded by Solana staking yield. Orchestrates other agents via A2A.',
    version: '1.0.0',
    url: `${process.env.AGENT_A_URL ?? 'http://localhost:3001'}/api/a2a`,
    capabilities: ['streaming'],
    defaultInputModes: ['text/plain'],
    defaultOutputModes: ['text/plain', 'application/json'],
    skills: [
      {
        name: 'chat',
        description: 'AI analysis and conversation, funded by user yield treasury',
        inputSchema: {
          type: 'object',
          properties: {
            query: { type: 'string' },
            userWallet: { type: 'string' },
          },
          required: ['query', 'userWallet'],
        },
      },
    ],
  })
})
